FROM bitnami/keycloak:latest

# Add TLS files into the container keycloak certificates directory
WORKDIR /opt/bitnami/keycloak/certs/

# pskey.keystore password is 123456
ADD ./pskey.keystore .

# hrms.truststore password is 234567
ADD ./hrms.truststore .

# truststore.jks password is 123456
ADD ./truststore.jks .

# for demonstration purposes only, please make sure to use proper certificates in production instead
# Add temporary validity new keys pair in pskey.keystore
#RUN keytool -genkeypair -storepass 123456 -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore server.keystore
