# This is a basic workflow to backup repository to BitBucket remote backup space

name: Mirror to BitBucket GitHub Action

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Initial checkout
        uses: action/checkout@v2
        with:
          fetch-depth: 0 # <-- clone with complete history
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # <-- clone with complete history
      - name: Push
        uses: ./ # Uses an action in the root directory
        id: mirror-to-bitbucket
        with:
          # Password to use on bitbucket for authentication and for pushing
          password: ${{ secrets.BITBUCKET_PASSWORD }}
          # Username to use on bitbucket for 1) authentication and as 2) workspace name. Default: GitHub user name
          username: ${{ secrets.BITBUCKET_USERNAME }}
          # Name of the repository on bitbucket. If it does not exist, it is created automatically. Default: GitHub repository name.
          repository: foundation-techstack-backup
