name: Sync main branch to Bitbucket (https://github.com/marketplace/actions/sync-git-branch-action)
on: [push, delete, create]
jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: zent-contrib/git-branch-sync-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.BITBUCKET_ACCESS_KEY }}
        with:
          source-branch: main
          destination-repo: "git@bitbucket.org:agnet/foundation-techstack-backup.git"
