name: Artifacts Repository Refresh
run-name: COMMIT STAGE - Version repository publishing
on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      target_repository:
        description: 'Type of release type (SNAPSHOT, RELEASE) to publish to dedicated Maven artifacts repository'
        required: false
        default: 'SNAPSHOT'
        type: string
      package_release_name:
        description: 'Name of the artifacts version to publish to a Maven repository'
        required: true
        type: string
      pom-base-path:
        description: 'Path to the pom.xml of the source project to deploy'
        required: true
        type: string

jobs:
  build_and_deploy_packages:
    name: Build and deploy to remote repository
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      ARTIFACT_VERSION: ${{ inputs.package_release_name }}
      MAVEN_USERNAME: ${{ secrets.AGNET_REPO_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.AGNET_REPO_PASSWORD }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password
    steps:
      - name: Checkout source codes from branch to publish
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
          ref: ${{ inputs.config-path }}

      - name: Set up Java for publishing to Maven repository
        uses: actions/setup-java@v4
        with: # running setup-java again overwrites the settings.xml
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          server-id: agnet # Value of the distributionManagement/repository/id filed of the pom.xml
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value (without an modification than exported by the gpg --export-secret-keys command) of the GPG private key (33105BFD367D25B3) to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: GitHub environment variables
        if: ${{ env.ARTIFACT_VERSION == '' }}
        uses: FranzDiebold/github-env-vars-action@v2.7.0

      - name: Define an unique revision name (pattern <<feature branch name>>.<<commit id abbrev>>.<<commit time>>)
        if: ${{ env.ARTIFACT_VERSION == '' }}
        run: |
            echo "Git commit revision $CI_SHA_SHORT abbreviation based on 7 characters (default) maximum (origin based: $CI_SHA)"
            echo "commit_id=$CI_SHA_SHORT" >> $GITHUB_ENV
            echo "feature_name=$CI_ACTION_REF_NAME_SLUG" >> $GITHUB_ENV

      - name: Identify the origin release name
        if: ${{ env.ARTIFACT_VERSION == '' }}
        # Define a static version name because not received from input parameter
        run: |
            echo "Define a final version identifier aligned with versioning strategy (<<version name>>-<<feature name>>.<<commit_id>>)"
            echo "current_artifacts_revision_id=${{ env.feature_name }}.${{ env.commit_id }}" >> $GITHUB_ENV
            echo "Development version type is defined as snapshot based on $CI_SHA_SHORT commit revision number"

      - name: Define the artifacts revision name to publish
        if: ${{ inputs.package_release_name != '' }}
        run: echo "current_artifacts_revision_id=${{ env.ARTIFACT_VERSION }}" >> $GITHUB_ENV

      - name: Snapshots remote repository is targeted to be updated
        if: ${{ contains(inputs.target_repository, 'SNAPSHOT') || inputs.target_repository == '' }}
        run: |
            echo "current_artifacts_revision_id=${{ env.current_artifacts_revision_id }}" >> $GITHUB_ENV
            echo "Snapshot packages will be published"

      - name: Prepare a customized ${{ env.current_artifacts_revision_id }} version to publish
        run: |
            cd ${{ inputs.pom-base-path }}
            echo "Set the artifacts version in pom.xml files"
            echo "mvn -B -DgenerateBackupPoms=true -DprocessAllModules=true versions:set -DnewVersion=${{ env.current_artifacts_revision_id }}"

      - name: Build and deploy ${{ env.current_artifacts_revision_id }} version of packages to AGNet repository (phases validate, compile, test, package, verify, install, deploy)
        run: |
            cd ${{ inputs.pom-base-path }}
            mvn --batch-mode --update-snapshots --show-version -Drevision=${{ env.current_artifacts_revision_id }} --file pom.xml -DcreateChecksum=true -Denvironment=dev-deploy deploy -Dmaven.test.skip=true

      - name: Deploy ${{ env.current_artifacts_revision_id }} version to Maven Central repository
        if: ${{ contains(inputs.target_repository, 'RELEASE') }}
        run: |
            cd ${{ inputs.pom-base-path }}
            mvn --batch-mode --show-version -Drevision=${{ env.current_artifacts_revision_id }} --file pom.xml -DcreateChecksum=true -Dstage=central-deploy deploy -Dmaven.test.skip=true
        env:
            MAVEN_USERNAME: ${{ secrets.MAVEN_OSS_REPO_USERNAME }}
            MAVEN_PASSWORD: ${{ secrets.MAVEN_OSS_REPO_PASSWORD }}
            MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_OSS_REPO_PASSWORD }}
